[package]
name = "hyperlane-core"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# These dependencies are incompatible with Solana programs
[target.'cfg(not(target_os = "solana"))'.dependencies]
ethers-contract.workspace = true
ethers-providers.workspace = true

[dependencies]
async-trait.workspace = true
auto_impl = "1.0"
borsh.workspace = true
bytes = { version = "1", features = ["serde"] }
config = { workspace = true, optional = true }
convert_case = "0.6"
derive-new.workspace = true
ethers-core.workspace = true
eyre.workspace = true
hex.workspace = true
itertools.workspace = true
num = { workspace = true, features = ["serde"] }
num-derive.workspace = true
num-traits.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3 = "0.10"
strum.workspace = true
thiserror.workspace = true

lazy_static.workspace = true
primitive-types = { version = "*", features = ["impl-borsh", "impl-serde"] }
derive_more.workspace = true

[dev-dependencies]
hyperlane-base = { path = "../hyperlane-base" }
tokio = { workspace = true, features = ["rt", "time"] }
walkdir = { version = "2" }

[features]
default = []
test-utils = ["dep:config"]
