[package]
name = "hyperlane-core"
version = "0.1.0"
edition = "2021"

[dependencies]
auto_impl = "1.0"
lazy_static.workspace = true
# TODO Use upstream primitive_types
primitive-types = { branch = "steven/primitive-types-impl-borsh", features = ["impl-borsh", "impl-serde"], git = "https://github.com/Eclipse-Laboratories-Inc/parity-common" }
sha3 = "0.10.0"
thiserror.workspace = true
serde.workspace = true
strum = { workspace = true, features = ["derive"] }
strum_macros.workspace = true
num-traits.workspace = true
num-derive.workspace = true
derive_more.workspace = true

# https://github.com/solana-labs/solana/blob/master/docs/src/developing/on-chain-programs/developing-rust.md#depending-on-rand
getrandom = { version = "0.2.2", features = ["custom"] }

borsh.workspace = true
bs58.workspace = true

[dev-dependencies]
serde_json.workspace = true
