[package]
name = "hyperlane-sealevel-multisig-ism-message-id"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
multisig-ism = { path = "../../../libraries/multisig-ism" }
num-derive.workspace = true
num-traits.workspace = true
solana-program = "=1.14.13"
account-utils = { path = "../../../libraries/account-utils" }
access-control = { path = "../../../libraries/access-control" }
ecdsa-signature = { path = "../../../libraries/ecdsa-signature" }
hyperlane-core = { path = "../../../../hyperlane-core" }
hyperlane-sealevel-mailbox = { path = "../../mailbox", features = ["no-entrypoint"] }
hyperlane-sealevel-interchain-security-module-interface = { path = "../../../libraries/interchain-security-module-interface" }
serializable-account-meta = { path = "../../../libraries/serializable-account-meta" }
thiserror.workspace = true

[dev-dependencies]
solana-program-test = "=1.14.13"
solana-sdk = "=1.14.13"
hex = "0.4.3"
multisig-ism = { path = "../../../libraries/multisig-ism", features = ["test-data"] }

[lib]
crate-type = ["cdylib", "lib"]
