[package]
name = "gelato"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1.56" }
derive_more = "0.99.0"
ethers = { git = "https://github.com/gakonst/ethers-rs", branch = "master" }
num-traits = "0.2"
num-derive = "0.3"
tokio = { version = "1.18.2", features = ["macros"] }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
reqwest = { version = "*", features = ["json"]}
rustc-hex = { version = "*" }
thiserror = { version = "*" }
tracing = "0.1"

[dev-dependencies]
clap = { version = "3.1.18", features = ["cargo", "derive"] }
tracing-subscriber = "0.2.0"

# TODO(webbhorn): Merge this into abacus-cli after we migrate it to `clap`.
[[example]]
name = "gelato-cli"
path = "examples/gelato_cli.rs"
