cargo-features = ["workspace-inheritance"]

[package]
name = "serializable-account-meta"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
solana-program.workspace = true

# Required to allow dependencies `getrandom` but to preserve determinism required by programs, see
# https://github.com/solana-labs/solana/blob/master/docs/src/developing/on-chain-programs/developing-rust.md#depending-on-rand
getrandom = { version = "0.2", features = ["custom"] }

[lib]
crate-type = ["cdylib", "lib"]
