[package]
name = "hyperlane-fuel"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0"
async-trait = { version = "0.1", default-features = false }
fuels = "0.33"
hyperlane-core = { path = "../../hyperlane-core" }
serde = "1.0"
thiserror = "1.0"
tracing = { version = "0.1", features = ["release_max_level_debug"] }
tracing-futures = "0.2"
url.workspace = true

[build-dependencies]
abigen = { path = "../../utils/abigen", features = ["fuels"] }
