[package]
name = "access-control"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program.workspace = true

[dev-dependencies]
solana-program-test.workspace = true
solana-sdk.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
