[package]
name = "hyperlane-sealevel-mailbox"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
hyperlane-core = { path = "../../../hyperlane-core" }
borsh.workspace = true
num-derive.workspace = true
num-traits.workspace = true
solana-program = "=1.14.13"
thiserror.workspace = true
access-control = { path = "../../libraries/access-control" }
account-utils = { path = "../../libraries/account-utils" }
serializable-account-meta = { path = "../../libraries/serializable-account-meta" }
hyperlane-sealevel-message-recipient-interface = { path = "../../libraries/message-recipient-interface" }
hyperlane-sealevel-interchain-security-module-interface = { path = "../../libraries/interchain-security-module-interface" }

bs58.workspace = true # FIXME remove

[dependencies.spl-noop]
version = "=0.1.3"
features = ["no-entrypoint"]
git = "https://github.com/tkporter/eclipse-program-library"
rev = "2f7e864"

[dev-dependencies]
base64 = "0.13"
itertools.workspace = true
log = "0.4"

[lib]
crate-type = ["cdylib", "lib"]
