[package]
name = "hyperlane-sealevel-client"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh.workspace = true
clap = { version = "4", features = ["derive"] }
account-utils = { path = "../libraries/account-utils" }
hyperlane-core = { path = "../../hyperlane-core" }
hyperlane-sealevel-multisig-ism-message-id = { path = "../programs/ism/multisig-ism-message-id" }
hyperlane-sealevel-mailbox = { path = "../programs/mailbox" }
hyperlane-sealevel-token = { path = "../programs/hyperlane-sealevel-token" }
hyperlane-sealevel-token-collateral = { path = "../programs/hyperlane-sealevel-token-collateral" }
hyperlane-sealevel-token-native = { path = "../programs/hyperlane-sealevel-token-native" }
hyperlane-sealevel-token-lib = { path = "../libraries/hyperlane-sealevel-token" }
hyperlane-sealevel-connection-client = { path = "../libraries/hyperlane-sealevel-connection-client" }
hyperlane-sealevel-validator-announce = { path = "../programs/validator-announce" }
lazy_static.workspace = true
pretty_env_logger = "0.4"
solana-client = "=1.14.13"
solana-cli-config = "=1.14.13"
solana-clap-utils = "=1.14.13"
solana-program = "=1.14.13"
solana-sdk = "=1.14.13"
hex = "0.4.3"
serde.workspace = true
serde_json.workspace = true
