[package]
name = "hyperlane-sealevel-mailbox"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
no-spl-noop = []

[dependencies]
hyperlane-core = { path = "../../hyperlane-core" }
borsh = "0.9"
solana-program = "=1.14.13"
access-control = { path = "../../libraries/access-control" }
account-utils = { path = "../../libraries/account-utils" }
serializable-account-meta = { path = "../../libraries/serializable-account-meta" }

[dev-dependencies]

[lib]
crate-type = ["cdylib", "lib"]
