cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-sealevel-token-native"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
bs58.workspace = true # FIXME remove
num-derive.workspace = true
num-traits.workspace = true
solana-program.workspace = true
spl-noop.workspace = true
thiserror.workspace = true

account-utils = { path = "../../libraries/account-utils" }
hyperlane-core = { path = "../../../hyperlane-core" }
hyperlane-sealevel-connection-client = { path = "../../libraries/hyperlane-sealevel-connection-client" }
hyperlane-sealevel-mailbox = { path = "../mailbox", features = ["no-entrypoint"] }
hyperlane-sealevel-message-recipient-interface = { path = "../../libraries/message-recipient-interface" }
hyperlane-sealevel-token-lib = { path = "../../libraries/hyperlane-sealevel-token" }
serializable-account-meta = { path = "../../libraries/serializable-account-meta" }

[lib]
crate-type = ["cdylib", "lib"]
