[package]
name = "hyperlane-sealevel-validator-announce"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
solana-program.workspace = true
thiserror.workspace = true

account-utils = { path = "../../libraries/account-utils" }
ecdsa-signature = { path = "../../libraries/ecdsa-signature" }
hyperlane-core = { path = "../../../hyperlane-core" }
hyperlane-sealevel-mailbox = { path = "../mailbox", features = ["no-entrypoint"] }
serializable-account-meta = { path = "../../libraries/serializable-account-meta" }

[dev-dependencies]
hex.workspace = true
solana-program-test.workspace = true
solana-sdk.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
