[package]
name = "hyperlane-sealevel"
version = "0.1.0"
edition = "2021"

[dependencies]
hyperlane-core = { path = "../../hyperlane-core" }
async-trait.workspace = true
thiserror.workspace = true
serde.workspace = true
anyhow.workspace = true
tracing-futures.workspace = true
tracing.workspace = true
num-traits.workspace = true
borsh.workspace = true
jsonrpc-core.workspace = true
url.workspace = true
base64.workspace = true

solana = { path = "./solana" }
