[package]
name = "hyperlane-sealevel"
version = "0.1.0"
edition = "2021"

[dependencies]
hyperlane-core = { path = "../../hyperlane-core" }
async-trait.workspace = true
thiserror.workspace = true
serde.workspace = true
anyhow.workspace = true
tracing-futures.workspace = true
tracing.workspace = true

# FIXME sealevel mailbox contract copypasta deps
borsh.workspace = true

# FIXME solana copypasta deps
bincode.workspace = true
blake3 = { workspace = true, features = ["digest", "traits-preview"] }
bs58.workspace = true
base64.workspace = true
ed25519-dalek.workspace = true
generic-array.workspace = true
Inflector.workspace = true
jsonrpc-core.workspace = true
lazy_static.workspace = true
num-traits.workspace = true
log.workspace = true
semver.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["full"] }
url.workspace = true
reqwest = { workspace = true, default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }

rand = "*"
# auto-resolve zstd version to avoid dependency conflicts
zstd = "*"
