[package]
name = "hyperlane-sealevel-validator-announce-test"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
borsh.workspace = true
solana-program.workspace = true
thiserror.workspace = true

account-utils = { path = "../../libraries/account-utils" }
ecdsa-signature = { path = "../../libraries/ecdsa-signature" }
hyperlane-core = { path = "../../../hyperlane-core" }
hyperlane-sealevel-mailbox = { path = "../mailbox", features = ["no-entrypoint"] }
serializable-account-meta = { path = "../../libraries/serializable-account-meta" }
hyperlane-sealevel-validator-announce = { path = "../validator-announce" }

hex.workspace = true
solana-program-test = "1.14.13"
solana-sdk.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
