# this cannot use the workspace since it is used by the patch script!

[package]
name = "patcher"
version = "0.4.16"
edition = "2021"


[dependencies]
which = "4.4.0"
cargo_toml = "0.15.3"
toml = "0.7.1"
pathdiff = "0.2.1"
