[package]
name = "patcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
which.workspace = true
md5.workspace = true

[[bin]]
name = "test-patcher"
path = "test-patcher.rs"
