[package]
name = "account-utils"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
solana-program.workspace = true
spl-type-length-value.workspace = true

[dev-dependencies]
solana-program-test.workspace = true
solana-sdk.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
